=== HBri7/IOTAChargeStation/open-plc-utils/docbook/piboffset.xsd
<?xml version='1.0' encoding='UTF-8'?>
<xs:schema xmlns:xs='http://www.w3.org/2001/XMLSchema' elementFormDefault='qualified'>
	<xs:element name='pib'>
		<xs:complexType>
			<xs:sequence>
				<xs:element maxOccurs='unbounded' ref='object'/>
				</xs:sequence>
			</xs:complexType>
		</xs:element>
	<xs:element name='object'>
		<xs:complexType>
			<xs:attribute name='name' use='required' type='xs:NCName'/>
			<xs:sequence>
				<xs:sequence>
					<xs:element ref='offset'/>
					<xs:element ref='length'/>
					</xs:sequence>
				<xs:choice>
					<xs:element ref='array'/>
					<xs:element ref='dataString'/>
					<xs:element ref='dataByte'/>
					</xs:choice>
				</xs:sequence>
			</xs:complexType>
		</xs:element>
	<xs:element name='length' type='xs:positiveInteger'/>
	<xs:element name='offset' type='xs:hexBinary'/>
	<xs:element name='array'>
		<xs:complexType>
			<xs:choice maxOccurs='unbounded'>
				<xs:element ref='dataByte'/>
				<xs:element ref='dataHex'/>
				</xs:choice>
			</xs:complexType>
		</xs:element>
	<xs:element name='dataString' type='xs:string'/>
	<xs:element name='dataHex' type='xs:hexBinary'/>
	<xs:element name='dataByte' type='xs:unsignedByte'/>
	</xs:schema>

=== HBri7/IOTAChargeStation/open-plc-utils/pib/piboffset.xml
<pib xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' xsi:noNamespaceSchemaLocation='piboffset.xsd'>
	<object name='FWMajorVersion'>
		<offset>
			0000
			</offset>
		<length>
			1
			</length>
		<dataHex>
			03
			</dataHex>
		</object>
	<object name='PIBMinorVersion'>
		<offset>
			0001
			</offset>
		<length>
			1
			</length>
		<dataHex>
			08
			</dataHex>
		</object>
	<object name='RSVD'>
		<offset>
			0002
			</offset>
		<length>
			2
			</length>
		<dataHex>
			0000
			</dataHex>
		</object>
	<object name='PIBLength'>
		<offset>
			0004
			</offset>
		<length>
			2
			</length>
		<dataHex>
			0820
			</dataHex>
		</object>
	<object name='RSVD'>
		<offset>
			0006
			</offset>
		<length>
			2
			</length>
		<dataHex>
			0000
			</dataHex>
		</object>
	<object name='Checksum'>
		<offset>
			0008
			</offset>
		<length>
			4
			</length>
		<dataHex>
			400BBA60
			</dataHex>
		</object>
	<object name='MACAddress'>
		<offset>
			000C
			</offset>
		<length>
			6
			</length>
		<dataHex>
			00B052000001
			</dataHex>
		</object>
	<object name='DAK'>
		<offset>
			0012
			</offset>
		<length>
			16
			</length>
		<dataHex>
			50D3E4933F855B7040784DF815AA8DB7
			</dataHex>
		</object>
	<object name='RSVD'>
		<offset>
			0022
			</offset>
		<length>
			2
			</length>
		<dataHex>
			0000
			</dataHex>
		</object>
	<object name='HFID_Manufacturer'>
		<offset>
			0024
			</offset>
		<length>
			64
			</length>
		<dataHex>
			496E74656C6C6F6E20486F6D65506C75672041562044657669636500000000000000000000000000000000000000000000000000000000000000000000000000
			</dataHex>
		</object>
	<object name='NMK'>
		<offset>
			0064
			</offset>
		<length>
			16
			</length>
		<dataHex>
			50D3E4933F855B7040784DF815AA8DB7
			</dataHex>
		</object>
	<object name='HFID_User'>
		<offset>
			0074
			</offset>
		<length>
			64
			</length>
		<dataHex>
			496E74656C6C6F6E20456E61626C65642050726F6475637400000000000000000000000000000000000000000000000000000000000000000000000000000000
			</dataHex>
		</object>
	<object name='HFID_AVLN'>
		<offset>
			00B4
			</offset>
		<length>
			64
			</length>
		<dataHex>
			496E74656C6C6F6E20456E61626C6564204E6574776F726B00000000000000000000000000000000000000000000000000000000000000000000000000000000
			</dataHex>
		</object>
	<object name='CCoSelection'>
		<offset>
			00F4
			</offset>
		<length>
			1
			</length>
		<dataHex>
			00
			</dataHex>
		</object>
	<object name='CoexistSelection'>
		<offset>
			00F5
			</offset>
		<length>
			1
			</length>
		<dataHex>
			00
			</dataHex>
		</object>
	<object name='PLFreqSelection'>
		<offset>
			00F6
			</offset>
		<length>
			1
			</length>
		<dataHex>
			00
			</dataHex>
		</object>
	<object name='RSV'>
		<offset>
			00F7
			</offset>
		<length>
			1
			</length>
		<dataHex>
			00
			</dataHex>
		</object>
	<object name='PreferredNID'>
		<offset>
			00F8
			</offset>
		<length>
			7
			</length>
		<dataHex>
			B0F2E695666B03
			</dataHex>
		</object>
	<object name='AutoFWUpgradeable'>
		<offset>
			00FF
			</offset>
		<length>
			1
			</length>
		<dataHex>
			00
			</dataHex>
		</object>
	<object name='MDUConfiguration'>
		<offset>
			0100
			</offset>
		<length>
			1
			</length>
		<dataHex>
			00
			</dataHex>
		</object>
	<object name='MDURole'>
		<offset>
			0101
			</offset>
		<length>
			1
			</length>
		<dataHex>
			00
			</dataHex>
		</object>
	<object name='SnifferEnable'>
		<offset>
			0102
			</offset>
		<length>
			1
			</length>
		<dataHex>
			00
			</dataHex>
		</object>
	<object name='SnifferReturnMACAddress'>
		<offset>
			0103
			</offset>
		<length>
			6
			</length>
		<dataHex>
			000000000000
			</dataHex>
		</object>
	<object name='RSVD'>
		<offset>
			0109
			</offset>
		<length>
			3
			</length>
		<dataHex>
			000000
			</dataHex>
		</object>
	<object name='StaticNetworkEnabled'>
		<offset>
			010C
			</offset>
		<length>
			1
			</length>
		<dataHex>
			00
			</dataHex>
		</object>
	<object name='LD_TEI'>
		<offset>
			010D
			</offset>
		<length>
			1
			</length>
		<dataHex>
			00
			</dataHex>
		</object>
	<object name='CCo_MACAdd'>
		<offset>
			010E
			</offset>
		<length>
			6
			</length>
		<dataHex>
			000000000000
			</dataHex>
		</object>
	<object name='SNID'>
		<offset>
			0114
			</offset>
		<length>
			1
			</length>
		<dataHex>
			00
			</dataHex>
		</object>
	<object name='NumPeerNodes'>
		<offset>
			0115
			</offset>
		<length>
			1
			</length>
		<dataHex>
			00
			</dataHex>
		</object>
	<object name='PeerNodes'>
		<offset>
			0116
			</offset>
		<length>
			56
			</length>
		<dataHex>
			0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
			</dataHex>
		</object>
	<object name='RSVD'>
		<offset>
			014E
			</offset>
		<length>
			62
			</length>
		<dataHex>
			0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
			</dataHex>
		</object>
	<object name='OverideDefaults'>
		<offset>
			018C
			</offset>
		<length>
			1
			</length>
		<dataHex>
			00
			</dataHex>
		</object>
	<object name='DisableFlowControl'>
		<offset>
			018D
			</offset>
		<length>
			1
			</length>
		<dataHex>
			00
			</dataHex>
		</object>
	<object name='AdvertisementCapabilities'>
		<offset>
			018E
			</offset>
		<length>
			1
			</length>
		<dataHex>
			00
			</dataHex>
		</object>
	<object name='OverrideDefaults'>
		<offset>
			018F
			</offset>
		<length>
			1
			</length>
		<dataHex>
			00
			</dataHex>
		</object>
	<object name='MaxFramesPerSec'>
		<offset>
			0190
			</offset>
		<length>
			4
			</length>
		<dataHex>
			00000000
			</dataHex>
		</object>
	<object name='DisableAutoNegotiation'>
		<offset>
			0194
			</offset>
		<length>
			1
			</length>
		<dataHex>
			00
			</dataHex>
		</object>
	<object name='EnetSpeedSetting'>
		<offset>
			0195
			</offset>
		<length>
			1
			</length>
		<dataHex>
			00
			</dataHex>
		</object>
	<object name='EnetDuplexSetting'>
		<offset>
			0196
			</offset>
		<length>
			1
			</length>
		<dataHex>
			00
			</dataHex>
		</object>
	<object name='DisableTxFlowControl'>
		<offset>
			0197
			</offset>
		<length>
			1
			</length>
		<dataHex>
			00
			</dataHex>
		</object>
	<object name='DisableRxFlowControl'>
		<offset>
			0198
			</offset>
		<length>
			1
			</length>
		<dataHex>
			00
			</dataHex>
		</object>
	<object name='PhyAddressSelection'>
		<offset>
			0199
			</offset>
		<length>
			1
			</length>
		<dataHex>
			00
			</dataHex>
		</object>
	<object name='PhyAddressSelection_Data'>
		<offset>
			019A
			</offset>
		<length>
			1
			</length>
		<dataHex>
			00
			</dataHex>
		</object>
	<object name='Force33Mhz'>
		<offset>
			019B
			</offset>
		<length>
			1
			</length>
		<dataHex>
			00
			</dataHex>
		</object>
	<object name='LinkStatusOnPowerline'>
		<offset>
			019C
			</offset>
		<length>
			1
			</length>
		<dataHex>
			00
			</dataHex>
		</object>
	<object name='OverrideIdDefaults'>
		<offset>
			019D
			</offset>
		<length>
			1
			</length>
		<dataHex>
			00
			</dataHex>
		</object>
	<object name='OverfideSubIdDefaults'>
		<offset>
			019E
			</offset>
		<length>
			1
			</length>
		<dataHex>
			00
			</dataHex>
		</object>
	<object name='OverrideDefaults'>
		<offset>
			019F
			</offset>
		<length>
			1
			</length>
		<dataHex>
			00
			</dataHex>
		</object>
	<object name='PCIDeviceID'>
		<offset>
			01A0
			</offset>
		<length>
			2
			</length>
		<dataHex>
			0000
			</dataHex>
		</object>
	<object name='PCIVendorID'>
		<offset>
			01A2
			</offset>
		<length>
			2
			</length>
		<dataHex>
			0000
			</dataHex>
		</object>
	<object name='RSVD'>
		<offset>
			01A4
			</offset>
		<length>
			1
			</length>
		<dataHex>
			00
			</dataHex>
		</object>
	<object name='PCIClassCode'>
		<offset>
			01A5
			</offset>
		<length>
			1
			</length>
		<dataHex>
			00
			</dataHex>
		</object>
	<object name='PCIClassCodeSubClass'>
		<offset>
			01A6
			</offset>
		<length>
			1
			</length>
		<dataHex>
			00
			</dataHex>
		</object>
	<object name='PCIRevisionID'>
		<offset>
			01A7
			</offset>
		<length>
			1
			</length>
		<dataHex>
			00
			</dataHex>
		</object>
	<object name='PCISubsystemID'>
		<offset>
			01A8
			</offset>
		<length>
			2
			</length>
		<dataHex>
			0000
			</dataHex>
		</object>
	<object name='PCISybsystemVendorID'>
		<offset>
			01AA
			</offset>
		<length>
			2
			</length>
		<dataHex>
			0000
			</dataHex>
		</object>
	<object name='RSVD'>
		<offset>
			01AC
			</offset>
		<length>
			64
			</length>
		<dataHex>
			00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
			</dataHex>
		</object>
	<object name='OverrideDefaults'>
		<offset>
			01EC
			</offset>
		<length>
			1
			</length>
		<dataHex>
			00
			</dataHex>
		</object>
	<object name='ConfigFlags'>
		<offset>
			01ED
			</offset>
		<length>
			1
			</length>
		<dataHex>
			00
			</dataHex>
		</object>
	<object name='NumCopiesToSend_PowerlineFrames'>
		<offset>
			01EE
			</offset>
		<length>
			1
			</length>
		<dataHex>
			00
			</dataHex>
		</object>
	<object name='RSVD'>
		<offset>
			01EF
			</offset>
		<length>
			29
			</length>
		<dataHex>
			0000000000000000000000000000000000000000000000000000000000
			</dataHex>
		</object>
	<object name='UniCastPriority'>
		<offset>
			020C
			</offset>
		<length>
			1
			</length>
		<dataHex>
			01
			</dataHex>
		</object>
	<object name='McastPriority'>
		<offset>
			020D
			</offset>
		<length>
			1
			</length>
		<dataHex>
			01
			</dataHex>
		</object>
	<object name='IGMPPriority'>
		<offset>
			020E
			</offset>
		<length>
			1
			</length>
		<dataHex>
			03
			</dataHex>
		</object>
	<object name='AVStreamPriority'>
		<offset>
			020F
			</offset>
		<length>
			1
			</length>
		<dataHex>
			02
			</dataHex>
		</object>
	<object name='PriorityTTL'>
		<offset>
			0210
			</offset>
		<length>
			16
			</length>
		<dataHex>
